version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: circleci/mongo:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "server/package.json" }}
      - run:
          name: install-npm
          command: cd server && npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "server/package.json" }}
          paths:
            - ./node_modules
     # - run:
     #     name: test-and-code-coverage
     #     command: cd server && './node_modules/.bin/nyc report --reporter=text-lcov npm test'
     # - store_artifacts:
     #     path: server/test-results.xml
     #     prefix: tests
     # - store_artifacts:
     #     path: server/coverage
     #     prefix: coverage
     # - store_test_results:
     #     path: server/test-results.xml
