version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: circleci/mongo:latest
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "server/package.json" }}
      - run:
          name: Install NPM packages
          command: npm ci
          working_directory: ./server
      - save_cache:
          key: dependency-cache-{{ checksum "server/package.json" }}
          paths:
            - ./server/node_modules
      - run:
          name: Run tests
          command: NODE_ENV=test ./node_modules/.bin/mocha --reporter mocha-junit-reporter --reporter-options mochaFile=./test/test-results.xml --recursive ./test --require babel-register --exit
          working_directory: ./server
      - run:
          name: Run code coverage
          command: NODE_ENV=test ./node_modules/.bin/nyc --reporter=html --report-dir=./test/coverage ./node_modules/.bin/mocha --recursive ./test --require babel-register --exit
          working_directory: ./server
      - store_test_results:
          path: server/test/
      - store_artifacts:
          path: server/test/coverage/
          prefix: coverage
