version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: circleci/mongo:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "server/package.json" }}
      - run:
          name: install-npm
          command: npm ci
          working_directory: ./server
      - save_cache:
          key: dependency-cache-{{ checksum "server/package.json" }}
          paths:
            - ./server/node_modules
      - run:
          name: test
          command: npm test
          working_directory: ./server
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
          working_directory: ./server
      - store_artifacts:
          path: server
          prefix: tests
      - store_artifacts:
          path: server/coverage
          prefix: coverage
      - store_test_results:
          path: server
